import { randomUUID } from 'node:crypto';
import { validateArtifact, type ArtifactValidationPolicy } from '../../shared/artifact-validators';
import type {
  ArtifactSchemaAsset,
  ArtifactQualityTier,
  RuntimeOutputRecord
} from '../../shared/types';
import { AiService, type ProviderSettings } from './ai-service';

export type StructuredGenerationResult = {
  content: string;
  outputs: RuntimeOutputRecord[];
  issues?: ReturnType<typeof validateArtifact>['issues'];
  repaired: boolean;
  accepted: boolean;
  qualityTier: ArtifactQualityTier;
  qualityScore: number;
  qualityReasons: string[];
  verdict: 'validated' | 'repaired' | 'degraded' | 'blocked';
  usedDeterministicFallback: boolean;
  message?: string;
};

function output(
  kind: RuntimeOutputRecord['kind'],
  label: string,
  contentType: RuntimeOutputRecord['contentType'],
  content: string,
  extras?: Partial<RuntimeOutputRecord>
): RuntimeOutputRecord {
  return {
    id: randomUUID(),
    createdAt: new Date().toISOString(),
    kind,
    label,
    contentType,
    content,
    ...extras
  };
}

function markdownFallback(schema: ArtifactSchemaAsset) {
  if (schema.deterministicFallbackContent?.trim()) {
    return schema.deterministicFallbackContent.trim();
  }

  const headings = schema.requiredHeadings?.length ? schema.requiredHeadings : ['#'];
  const lines: string[] = [];
  headings.forEach((heading, index) => {
    const title = index === 0 ? schema.title : `${schema.title} Supplement`;
    const resolvedHeading = /^#{1,6}\s+/.test(heading) ? heading : `${heading} ${title}`;
    lines.push(resolvedHeading, '');
    if (index > 0) {
      lines.push(
        '- This section was generated by the deterministic fallback template.',
        '- Fill in concrete users, constraints, evidence, and execution details before delivery.',
        ''
      );
    }
  });
  if (headings.length === 1) {
    lines.push(
      '- This document was generated by the deterministic fallback template.',
      '- Expand it with concrete facts, edge cases, and next actions before delivery.',
      ''
    );
  }
  return lines.join('\n');
}

function mermaidFallback(schema: ArtifactSchemaAsset) {
  return [
    'flowchart TD',
    `  Start[Start] --> Draft[Generate ${schema.title}]`,
    '  Draft --> Review[Validate output]',
    '  Review --> End[Done]',
    ''
  ].join('\n');
}

function reviewIssuesFallback() {
  return [
    '- Manual review is required for the current output structure.',
    '- Add more execution details and explicit failure paths before delivery.',
    ''
  ].join('\n');
}

function uiPreviewFallback() {
  return JSON.stringify({
    version: 1,
    theme: 'light',
    layout: {
      type: 'workspace',
      columns: ['sidebar', 'document', 'assistant']
    }
  }, null, 2);
}

function openspecFallback() {
  return [
    '# Delivery Summary',
    '',
    '## Current Status',
    '',
    '- A deterministic fallback summary was generated.',
    '- Manual completion is required before final delivery.',
    ''
  ].join('\n');
}

function buildDeterministicFallback(schema: ArtifactSchemaAsset) {
  switch (schema.kind) {
    case 'mermaid':
      return mermaidFallback(schema);
    case 'review-issues':
      return reviewIssuesFallback();
    case 'ui-preview':
      return uiPreviewFallback();
    case 'openspec-handoff':
      return openspecFallback();
    case 'text':
    case 'markdown':
    default:
      return markdownFallback(schema);
  }
}

function markdownRepairInstructionBlock(schema: ArtifactSchemaAsset) {
  const lines = [
    'Return only the repaired markdown artifact.',
    'Do not wrap the answer in code fences.',
    'Do not mention validators, repair steps, placeholders, TODO, TBD, or deterministic fallback.',
    'Preserve useful content from the raw output, but expand weak sections until the artifact is complete.'
  ];
  if (schema.requiredHeadings?.length) {
    lines.push(
      'Required headings:',
      ...schema.requiredHeadings.map((heading) => `- ${heading}`)
    );
  }
  if (typeof schema.minimumLength === 'number') {
    lines.push(`Minimum length: at least ${schema.minimumLength} characters.`);
  }
  lines.push(
    'If source information is incomplete, make best-effort concrete assumptions inside the artifact instead of asking the user follow-up questions.',
    'Add concrete bullets, constraints, inputs, outputs, examples, risks, and next actions when the draft is too short or too generic.'
  );
  return lines.join('\n');
}

function targetedRepairInstructionBlock(
  schema: ArtifactSchemaAsset,
  validation: ReturnType<typeof validateArtifact>
) {
  const hints = validation.repairHints ?? [];
  if (!hints.length) {
    return '';
  }
  return [
    `Targeted repair profile for ${schema.id}:`,
    ...hints.map((hint, index) => `${index + 1}. ${hint}`)
  ].join('\n');
}

function finalOutput(
  content: string,
  result: {
    qualityTier: ArtifactQualityTier;
    qualityScore: number;
    qualityReasons: string[];
    verdict: StructuredGenerationResult['verdict'];
    accepted: boolean;
  }
) {
  return output('final', 'validated-artifact', 'markdown', content, {
    qualityTier: result.qualityTier,
    qualityVerdict: result.verdict,
    qualityScore: result.qualityScore,
    qualityReasons: result.qualityReasons,
    accepted: result.accepted
  });
}

function resolveAcceptedFinalVerdict(input: {
  qualityVerdict: ReturnType<typeof validateArtifact>['qualityVerdict'];
  repaired: boolean;
}) {
  if (input.qualityVerdict === 'accepted') {
    return input.repaired ? 'repaired' : 'validated';
  }
  return 'degraded';
}

export class StructuredGenerationService {
  constructor(private readonly aiService: AiService) {}

  async generateText(settings: ProviderSettings, input: { system: string; user: string }) {
    const raw = await this.aiService.complete(settings, input);
    return {
      content: raw,
      output: output('final', 'text-output', 'text', raw)
    };
  }

  async generateMarkdown(
    settings: ProviderSettings,
    input: { system: string; user: string },
    schema: ArtifactSchemaAsset,
    policy?: ArtifactValidationPolicy
  ) {
    const raw = await this.aiService.complete(settings, input);
    return this.coerceMarkdown(settings, input, schema, raw, policy);
  }

  async coerceMarkdown(
    settings: ProviderSettings,
    input: { system: string; user: string },
    schema: ArtifactSchemaAsset,
    raw: string,
    policy?: ArtifactValidationPolicy
  ) {
    const rawValidation = validateArtifact(raw, schema, policy);
    const rawOutput = output('raw', 'raw-model-output', 'markdown', raw, {
      qualityTier: rawValidation.qualityTier,
      qualityVerdict: rawValidation.qualityVerdict,
      qualityScore: rawValidation.qualityScore,
      qualityReasons: rawValidation.qualityReasons
    });
    if (rawValidation.ok) {
      return {
        content: rawValidation.normalized ?? raw,
        outputs: [
          rawOutput,
          finalOutput(rawValidation.normalized ?? raw, {
            qualityTier: rawValidation.qualityTier,
            qualityScore: rawValidation.qualityScore,
            qualityReasons: rawValidation.qualityReasons,
            verdict: 'validated',
            accepted: true
          })
        ],
        issues: rawValidation.issues,
        repaired: false,
        accepted: true,
        qualityTier: rawValidation.qualityTier,
        qualityScore: rawValidation.qualityScore,
        qualityReasons: rawValidation.qualityReasons,
        verdict: 'validated',
        usedDeterministicFallback: false,
        message: rawValidation.message
      } satisfies StructuredGenerationResult;
    }

    const repairInstructions = markdownRepairInstructionBlock(schema);
    const targetedRepairInstructions = targetedRepairInstructionBlock(schema, rawValidation);
    const repaired = await this.aiService.complete(settings, {
      system: [
        input.system,
        'You are repairing a markdown artifact that failed validation.',
        repairInstructions,
        targetedRepairInstructions
      ].filter(Boolean).join('\n\n'),
      user: [
        input.user,
        '',
        'Artifact constraints:',
        repairInstructions,
        targetedRepairInstructions ? `\nTargeted repair guidance:\n${targetedRepairInstructions}` : '',
        '',
        'Previous raw output:',
        raw,
        '',
        `Validation issue: ${rawValidation.message ?? 'unknown'}`,
        ...(rawValidation.qualityReasons.length
          ? ['', 'Quality findings:', ...rawValidation.qualityReasons.map((reason) => `- ${reason}`)]
          : []),
        '',
        'Preserve useful content, but return a corrected final artifact only.'
      ].join('\n')
    });
    const repairedValidation = validateArtifact(repaired, schema, policy);
    const repairedOutput = output('repaired', 'repaired-model-output', 'markdown', repaired, {
      qualityTier: repairedValidation.qualityTier,
      qualityVerdict: repairedValidation.qualityVerdict,
      qualityScore: repairedValidation.qualityScore,
      qualityReasons: repairedValidation.qualityReasons
    });
    if (repairedValidation.ok) {
      const repairedVerdict = resolveAcceptedFinalVerdict({
        qualityVerdict: repairedValidation.qualityVerdict,
        repaired: true
      });
      return {
        content: repairedValidation.normalized ?? repaired,
        outputs: [
          rawOutput,
          repairedOutput,
          finalOutput(repairedValidation.normalized ?? repaired, {
            qualityTier: repairedValidation.qualityTier,
            qualityScore: repairedValidation.qualityScore,
            qualityReasons: repairedValidation.qualityReasons,
            verdict: repairedVerdict,
            accepted: true
          })
        ],
        issues: repairedValidation.issues,
        repaired: true,
        accepted: true,
        qualityTier: repairedValidation.qualityTier,
        qualityScore: repairedValidation.qualityScore,
        qualityReasons: repairedValidation.qualityReasons,
        verdict: repairedVerdict,
        usedDeterministicFallback: false,
        message: repairedValidation.message
      } satisfies StructuredGenerationResult;
    }

    const fallback = buildDeterministicFallback(schema);
    const fallbackValidation = validateArtifact(fallback, schema, policy);
    if (!fallbackValidation.structuralOk) {
      throw new Error(`Structured generation repair failed: ${repairedValidation.message}`);
    }

    const accepted = fallbackValidation.ok;
    const fallbackVerdict = accepted
      ? resolveAcceptedFinalVerdict({
          qualityVerdict: fallbackValidation.qualityVerdict,
          repaired: true
        })
      : 'blocked';
    return {
      content: fallbackValidation.normalized ?? fallback,
      outputs: [
        rawOutput,
        repairedOutput,
        output('repaired', 'deterministic-fallback', 'markdown', fallback, {
          qualityTier: fallbackValidation.qualityTier,
          qualityVerdict: fallbackValidation.qualityVerdict,
          qualityScore: fallbackValidation.qualityScore,
          qualityReasons: fallbackValidation.qualityReasons
        }),
        finalOutput(fallbackValidation.normalized ?? fallback, {
          qualityTier: fallbackValidation.qualityTier,
          qualityScore: fallbackValidation.qualityScore,
          qualityReasons: fallbackValidation.qualityReasons,
          verdict: fallbackVerdict,
          accepted
        })
      ],
      issues: fallbackValidation.issues,
      repaired: true,
      accepted,
      qualityTier: fallbackValidation.qualityTier,
      qualityScore: fallbackValidation.qualityScore,
      qualityReasons: fallbackValidation.qualityReasons,
      verdict: fallbackVerdict,
      usedDeterministicFallback: true,
      message: fallbackValidation.message
    } satisfies StructuredGenerationResult;
  }
}
