import { parseUiPreviewSpec } from './ui-preview';
import type {
  ArtifactQualityTier,
  ArtifactQualityVerdict,
  ArtifactSchemaAsset,
  ReviewIssue
} from './types';

export type ArtifactValidationPolicy = {
  qualityTier?: ArtifactQualityTier;
  minimumQualityScore?: number;
};

export type ArtifactValidationResult = {
  ok: boolean;
  structuralOk: boolean;
  message?: string;
  normalized?: string;
  issues?: ReviewIssue[];
  repairHints?: string[];
  qualityTier: ArtifactQualityTier;
  qualityVerdict: ArtifactQualityVerdict;
  qualityScore: number;
  qualityReasons: string[];
};

const DEFAULT_MINIMUM_SCORES: Record<ArtifactQualityTier, number> = {
  strict: 72,
  assistive: 45
};

const DEFAULT_STRICT_SCHEMA_IDS = new Set([
  'requirements-discovery',
  'requirements-clarify',
  'feature-tree',
  'feature-list',
  'technology-solution',
  'implementation-solution',
  'auto-test-plan',
  'manual-acceptance',
  'delivery-summary',
  'openspec-handoff'
]);

const DEFAULT_SCHEMA_SCORE_OVERRIDES = new Map<string, number>([
  ['requirements-discovery', 84],
  ['requirements-clarify', 84],
  ['feature-tree', 74],
  ['feature-list', 74],
  ['technology-solution', 76],
  ['implementation-solution', 76],
  ['auto-test-plan', 72],
  ['manual-acceptance', 72],
  ['delivery-summary', 72],
  ['openspec-handoff', 72]
]);

const DETERMINISTIC_FALLBACK_PATTERNS = [
  'This section was generated by the deterministic fallback template.',
  'This document was generated by the deterministic fallback template.',
  'Fill in concrete users, constraints, evidence, and execution details before delivery.',
  'Expand it with concrete facts, edge cases, and next actions before delivery.'
];

const PLACEHOLDER_PATTERNS = [
  'before delivery',
  'fill in concrete',
  'expand it with concrete facts',
  'needs manual follow-up',
  'placeholder',
  'TBD',
  'TODO'
];

function stripMarkdownCodeLiterals(raw: string) {
  return raw
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`\r\n]+`/g, ' ');
}

function stripPlaceholderPolicyLines(raw: string) {
  return raw
    .split(/\r?\n/)
    .filter((line) => {
      const normalized = line.toLowerCase();
      const mentionsPlaceholderPattern = PLACEHOLDER_PATTERNS.some((pattern) =>
        normalized.includes(pattern.toLowerCase())
      );
      if (!mentionsPlaceholderPattern) {
        return true;
      }

      return !/\b(no|not|without|avoid|reject|block|forbid|prohibit)\b|must not|should not|不得|不能|不要|禁止|无/.test(normalized);
    })
    .join('\n');
}

type MarkdownSectionContract = {
  heading: string;
  minBulletCount: number;
  requiredSignals: RegExp[];
  repairHint: string;
};

type MarkdownQualityProfile = {
  id: string;
  targetLength: number;
  minimumSpecificitySignals: number;
  minimumActionabilitySignals: number;
  sectionContracts: MarkdownSectionContract[];
  wholeDocumentRules: Array<{
    id: string;
    test: (markdown: string) => boolean;
    reason: string;
    repairHint: string;
  }>;
};

const DISCOVERY_PROFILE: MarkdownQualityProfile = {
  id: 'requirements-discovery',
  targetLength: 760,
  minimumSpecificitySignals: 3,
  minimumActionabilitySignals: 3,
  sectionContracts: [
    {
      heading: '## 目标用户',
      minBulletCount: 2,
      requiredSignals: [/(用户|角色|团队|负责人|执行者|内容|创作|读者|运营|使用者)/i, /(场景|任务|负责|需要|用于|使用|在.+时)/i],
      repairHint: '在“## 目标用户”下写清至少两类用户或角色，并说明他们分别在哪些场景下使用该产品。'
    },
    {
      heading: '## 核心问题',
      minBulletCount: 2,
      requiredSignals: [/(问题|痛点|困难|缺少|无法|低效|返工|遗漏|混乱|断裂)/i],
      repairHint: '在“## 核心问题”下写清当前流程的具体痛点、低效点、信息断裂或返工风险。'
    },
    {
      heading: '## 核心价值',
      minBulletCount: 2,
      requiredSignals: [/(价值|帮助|提升|减少|统一|沉淀|加速|复用|提高|降低)/i],
      repairHint: '在“## 核心价值”下写清产品带来的明确收益，而不是泛泛描述“更好”或“更方便”。'
    },
    {
      heading: '## 显性限制',
      minBulletCount: 2,
      requiredSignals: [/(限制|约束|边界|仅|必须|不能|不做|范围|兼容|本地|阶段)/i],
      repairHint: '在“## 显性限制”下写清阶段边界、必须满足的限制条件和明确不做的范围。'
    },
    {
      heading: '## 待确认问题',
      minBulletCount: 2,
      requiredSignals: [/(是否|待确认|未决|未知|还需|需要补充|确认|？|\?)/i],
      repairHint: '在“## 待确认问题”下列出仍需确认的开放问题，并尽量用问句或明确的待确认项表达。'
    }
  ],
  wholeDocumentRules: [
    {
      id: 'discover-success-criteria',
      test: (markdown) => /(成功标准|验收标准|成功判定|衡量方式|完成标准|验收条件)/i.test(markdown),
      reason: 'discover artifact is missing explicit success criteria',
      repairHint: '在“## 核心价值”或“## 显性限制”中补写成功标准、验收条件或衡量方式。'
    },
    {
      id: 'discover-next-actions',
      test: (markdown) => /(下一步|后续|接下来|澄清动作|确认动作|进入澄清|后续阶段)/i.test(markdown),
      reason: 'discover artifact is missing next clarification actions',
      repairHint: '补写下一步应该确认什么、进入哪个阶段以及后续澄清动作。'
    }
  ]
};

const CLARIFY_PROFILE: MarkdownQualityProfile = {
  id: 'requirements-clarify',
  targetLength: 820,
  minimumSpecificitySignals: 3,
  minimumActionabilitySignals: 3,
  sectionContracts: [
    {
      heading: '## 使用方式',
      minBulletCount: 2,
      requiredSignals: [/(步骤|操作|流程|进入|点击|切换|生成|编辑|保存|导出|工作台|页面)/i],
      repairHint: '在“## 使用方式”下按用户实际操作流程写清主要步骤，而不是只写抽象目标。'
    },
    {
      heading: '## 输入与输出',
      minBulletCount: 2,
      requiredSignals: [/(输入|输出|格式|目录|文件|文档|md|pdf|txt|表格|工件|路径|结构)/i],
      repairHint: '在“## 输入与输出”下写清输入物、输出物、格式、目录结构或工件类型。'
    },
    {
      heading: '## 关键约束',
      minBulletCount: 2,
      requiredSignals: [/(约束|必须|不能|限制|权限|兼容|安全|成本|性能|本地|模型)/i],
      repairHint: '在“## 关键约束”下写清不可违反的限制，如平台、权限、安全、模型或性能要求。'
    },
    {
      heading: '## 风险与边界',
      minBulletCount: 2,
      requiredSignals: [/(风险|边界|失败|异常|冲突|恢复|降级|不做|超出|损坏|误用)/i],
      repairHint: '在“## 风险与边界”下写清失败场景、异常路径、系统边界和不覆盖的情况。'
    },
    {
      heading: '## 待确认问题',
      minBulletCount: 2,
      requiredSignals: [/(是否|待确认|未决|未知|还需|确认|？|\?)/i],
      repairHint: '在“## 待确认问题”下列出仍未确认的关键问题，不要留成空泛占位。'
    }
  ],
  wholeDocumentRules: [
    {
      id: 'clarify-next-stage-inputs',
      test: (markdown) => /(下一阶段|后续阶段|交付输入|进入方案|进入计划|基线输入|下游输入)/i.test(markdown),
      reason: 'clarify artifact is missing explicit next-stage inputs',
      repairHint: '补写这些澄清信息将如何作为下一阶段的输入、基线或交付前置条件。'
    },
    {
      id: 'clarify-output-contracts',
      test: (markdown) => /(输出格式|目录结构|工件|文档结构|输出目录|文件格式)/i.test(markdown),
      reason: 'clarify artifact is missing explicit output contract details',
      repairHint: '补写输出格式、目录结构、工件类型或文档结构要求，避免只停留在笼统描述。'
    }
  ]
};

function markdownQualityProfile(schema: ArtifactSchemaAsset) {
  switch (schema.id) {
    case 'requirements-discovery':
      return DISCOVERY_PROFILE;
    case 'requirements-clarify':
      return CLARIFY_PROFILE;
    default:
      return null;
  }
}

function extractMarkdownSections(markdown: string) {
  const lines = markdown.split(/\r?\n/);
  const sections = new Map<string, string[]>();
  let currentHeading = '';
  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    if (/^##\s+/.test(line)) {
      currentHeading = line.trim();
      if (!sections.has(currentHeading)) {
        sections.set(currentHeading, []);
      }
      continue;
    }
    if (currentHeading) {
      sections.get(currentHeading)?.push(line);
    }
  }
  return sections;
}

function countBullets(lines: string[]) {
  return lines.filter((line) => /^\s*[-*]\s+/.test(line)).length;
}

function countMarkdownTableRows(markdown: string) {
  const tableLines = markdown
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => /^\|.*\|$/.test(line));
  const contentRows = tableLines.filter((line) => !/^\|(?:\s*:?-+:?\s*\|)+$/.test(line));
  return Math.max(0, contentRows.length - 1);
}

function evaluateMarkdownProfile(markdown: string, schema: ArtifactSchemaAsset) {
  const profile = markdownQualityProfile(schema);
  if (!profile) {
    return {
      bonus: 0,
      penalties: [] as string[],
      repairHints: [] as string[],
      targetLength: null as number | null,
      specificityFloor: 0,
      actionabilityFloor: 0
    };
  }

  const sections = extractMarkdownSections(markdown);
  const penalties: string[] = [];
  const repairHints = new Set<string>();
  let satisfied = 0;

  for (const contract of profile.sectionContracts) {
    const lines = sections.get(contract.heading) ?? [];
    const bullets = countBullets(lines);
    const sectionText = lines.join('\n');
    const signalMatches = contract.requiredSignals.filter((pattern) => pattern.test(sectionText)).length;
    if (bullets < contract.minBulletCount || signalMatches < Math.min(1, contract.requiredSignals.length)) {
      penalties.push(`${contract.heading} lacks concrete, stage-specific detail`);
      repairHints.add(contract.repairHint);
      continue;
    }
    satisfied += 1;
  }

  for (const rule of profile.wholeDocumentRules) {
    if (!rule.test(markdown)) {
      penalties.push(rule.reason);
      repairHints.add(rule.repairHint);
      continue;
    }
    satisfied += 1;
  }

  return {
    bonus: Math.min(18, satisfied * 3),
    penalties,
    repairHints: Array.from(repairHints),
    targetLength: profile.targetLength,
    specificityFloor: profile.minimumSpecificitySignals,
    actionabilityFloor: profile.minimumActionabilitySignals
  };
}

export function resolveArtifactValidationPolicy(schema: ArtifactSchemaAsset, policy?: ArtifactValidationPolicy) {
  const inferredTier = DEFAULT_STRICT_SCHEMA_IDS.has(schema.id) ? 'strict' : 'assistive';
  const qualityTier = policy?.qualityTier ?? schema.qualityTier ?? inferredTier;
  const minimumQualityScore = policy?.minimumQualityScore
    ?? schema.minimumQualityScore
    ?? DEFAULT_SCHEMA_SCORE_OVERRIDES.get(schema.id)
    ?? DEFAULT_MINIMUM_SCORES[qualityTier];
  return {
    qualityTier,
    minimumQualityScore
  };
}

function buildResult(input: {
  structuralOk: boolean;
  qualityTier: ArtifactQualityTier;
  qualityVerdict: ArtifactQualityVerdict;
  qualityScore: number;
  qualityReasons?: string[];
  repairHints?: string[];
  message?: string;
  normalized?: string;
  issues?: ReviewIssue[];
}) {
  const qualityReasons = input.qualityReasons ?? [];
  const ok = input.structuralOk && (
    input.qualityVerdict === 'accepted'
    || (input.qualityTier === 'assistive' && input.qualityVerdict === 'degraded')
  );
  return {
    ok,
    structuralOk: input.structuralOk,
    message: input.message,
    normalized: input.normalized,
    issues: input.issues,
    repairHints: input.repairHints,
    qualityTier: input.qualityTier,
    qualityVerdict: input.qualityVerdict,
    qualityScore: Math.max(0, Math.min(100, Math.round(input.qualityScore))),
    qualityReasons
  } satisfies ArtifactValidationResult;
}

function scoreMarkdownQuality(
  raw: string,
  schema: ArtifactSchemaAsset,
  policy?: ArtifactValidationPolicy
): {
  qualityTier: ArtifactQualityTier;
  minimumQualityScore: number;
  qualityScore: number;
  qualityVerdict: ArtifactQualityVerdict;
  qualityReasons: string[];
  repairHints: string[];
} {
  const trimmed = raw.trim();
  const { qualityTier, minimumQualityScore } = resolveArtifactValidationPolicy(schema, policy);
  const headings = trimmed.match(/^#{1,6}\s+/gm) ?? [];
  const bullets = trimmed.match(/^\s*[-*]\s+/gm) ?? [];
  const tableRows = countMarkdownTableRows(trimmed);
  const enumerationMarkers = Math.max(bullets.length, schema.id === 'feature-list' ? tableRows : 0);
  const codeFenceCount = (trimmed.match(/```/g) ?? []).length;
  const placeholderScanSource = stripPlaceholderPolicyLines(stripMarkdownCodeLiterals(trimmed));
  const fallbackHits = DETERMINISTIC_FALLBACK_PATTERNS.filter((pattern) => placeholderScanSource.includes(pattern));
  const placeholderHits = PLACEHOLDER_PATTERNS.filter((pattern) => placeholderScanSource.toLowerCase().includes(pattern.toLowerCase()));
  const profile = evaluateMarkdownProfile(trimmed, schema);
  const targetLength = Math.max(
    schema.minimumLength ?? 0,
    profile.targetLength ?? 0,
    qualityTier === 'strict' ? 600 : 240
  );
  const specificitySignals = [
    /\d/.test(trimmed),
    /`[^`]+`/.test(trimmed),
    /(?:\/|\\)[A-Za-z0-9._/-]+/.test(trimmed),
    /(?:must|shall|need|risk|constraint|output|input|repair|evidence|artifact|stage|flow|node|用户|约束|风险|输出|输入|阶段|流程|证据|工件|节点|修复|回退)/i.test(trimmed)
  ].filter(Boolean).length;
  const actionabilitySignals = [
    /(?:must|shall|need|should|步骤|操作|执行|检查|验证|确认|修复|恢复|导出|回滚|输入|输出|约束|规则|阶段|流程|下一步)/i.test(trimmed),
    /\b(?:error|retry|recover|rollback|verify|check|acceptance|contract|export|input|output)\b/i.test(trimmed),
    /(?:\/|\\)[A-Za-z0-9._/-]+/.test(trimmed),
    /\d/.test(trimmed)
  ].filter(Boolean).length;

  let score = 0;
  const reasons: string[] = [];
  const repairHints = [...profile.repairHints];

  score += Math.min(35, Math.round((Math.min(trimmed.length, targetLength) / Math.max(targetLength, 1)) * 35));
  score += headings.length >= 6 ? 18 : headings.length >= 4 ? 15 : headings.length >= 3 ? 12 : headings.length >= 2 ? 8 : 2;
  score += enumerationMarkers >= 6 ? 12 : enumerationMarkers >= 3 ? 10 : enumerationMarkers >= 1 ? 6 : 0;
  score += Math.min(20, specificitySignals * 5);
  score += Math.min(10, actionabilitySignals * 3);
  score += codeFenceCount <= 12 ? 15 : 5;
  score += profile.bonus;

  if (trimmed.length < targetLength) {
    reasons.push(`length ${trimmed.length} below target ${targetLength}`);
  }
  if (headings.length < 3) {
    reasons.push(`only ${headings.length} markdown heading markers found`);
  }
  if (enumerationMarkers < 2) {
    reasons.push(schema.id === 'feature-list'
      ? `only ${enumerationMarkers} list or table markers found`
      : `only ${enumerationMarkers} list markers found`);
  }
  if (specificitySignals < Math.max(2, profile.specificityFloor)) {
    reasons.push('content specificity signals are weak');
  }
  if (actionabilitySignals < Math.max(2, profile.actionabilityFloor)) {
    reasons.push('content actionability signals are weak');
  }
  if (codeFenceCount > 12) {
    reasons.push(`too many code fences: ${codeFenceCount}`);
    score -= 10;
  }
  if (profile.penalties.length) {
    reasons.push(...profile.penalties);
    score -= Math.min(30, profile.penalties.length * 6);
  }
  if (placeholderHits.length) {
    reasons.push(`placeholder patterns detected: ${placeholderHits.join(', ')}`);
    score -= Math.min(35, placeholderHits.length * 14);
  }
  if (fallbackHits.length) {
    reasons.push(`deterministic fallback markers detected: ${fallbackHits.join(', ')}`);
    score = Math.min(score, 18);
  }

  score = Math.max(0, Math.min(100, score));
  if (reasons.length) {
    score = Math.min(score, 89);
  }

  if (fallbackHits.length) {
    return {
      qualityTier,
      minimumQualityScore,
      qualityScore: score,
      qualityVerdict: qualityTier === 'strict' ? 'blocked' : 'degraded',
      qualityReasons: reasons,
      repairHints
    };
  }
  if (score < minimumQualityScore) {
    reasons.unshift(`quality score ${score} below minimum ${minimumQualityScore}`);
    return {
      qualityTier,
      minimumQualityScore,
      qualityScore: score,
      qualityVerdict: 'degraded' as const,
      qualityReasons: reasons,
      repairHints
    };
  }
  if (reasons.length) {
    return {
      qualityTier,
      minimumQualityScore,
      qualityScore: score,
      qualityVerdict: 'degraded' as const,
      qualityReasons: reasons,
      repairHints
    };
  }
  return {
    qualityTier,
    minimumQualityScore,
    qualityScore: score,
    qualityVerdict: 'accepted' as const,
    qualityReasons: reasons,
    repairHints
  };
}

function validateMarkdown(raw: string, schema: ArtifactSchemaAsset, policy?: ArtifactValidationPolicy): ArtifactValidationResult {
  const trimmed = raw.trim();
  const { qualityTier } = resolveArtifactValidationPolicy(schema, policy);
  if (!trimmed) {
    return buildResult({
      structuralOk: false,
      qualityTier,
      qualityVerdict: 'blocked',
      qualityScore: 0,
      qualityReasons: ['markdown output is empty'],
      repairHints: ['先补齐该阶段的核心目标、约束、问题和后续动作，再重新生成文档。'],
      message: 'Markdown output is empty.'
    });
  }
  const headings = schema.requiredHeadings ?? [];
  for (const heading of headings) {
    if (!trimmed.includes(heading)) {
      return buildResult({
        structuralOk: false,
        qualityTier,
        qualityVerdict: 'blocked',
        qualityScore: 0,
        qualityReasons: [`missing required heading: ${heading}`],
        repairHints: [`补齐缺失标题“${heading}”对应的内容。`],
        message: `Missing required heading: ${heading}`
      });
    }
  }
  if (typeof schema.minimumLength === 'number' && trimmed.length < schema.minimumLength) {
    return buildResult({
      structuralOk: false,
      qualityTier,
      qualityVerdict: 'blocked',
      qualityScore: Math.round((trimmed.length / Math.max(schema.minimumLength, 1)) * 20),
      qualityReasons: [`length ${trimmed.length} below minimum ${schema.minimumLength}`],
      repairHints: ['补充更具体的约束、输入输出、风险、成功标准和下一步动作，避免只写短句摘要。'],
      message: `Markdown output is shorter than the minimum length: ${schema.minimumLength}.`
    });
  }

  const quality = scoreMarkdownQuality(trimmed, schema, policy);
  return buildResult({
    structuralOk: true,
    qualityTier: quality.qualityTier,
    qualityVerdict: quality.qualityVerdict,
    qualityScore: quality.qualityScore,
    qualityReasons: quality.qualityReasons,
    repairHints: quality.repairHints,
    message: quality.qualityVerdict === 'accepted'
      ? undefined
      : quality.qualityReasons[0] ?? `Quality score ${quality.qualityScore} below threshold.`,
    normalized: trimmed.endsWith('\n') ? trimmed : `${trimmed}\n`
  });
}

function validateMermaid(raw: string, schema: ArtifactSchemaAsset, policy?: ArtifactValidationPolicy): ArtifactValidationResult {
  const trimmed = raw.trim();
  const { qualityTier } = resolveArtifactValidationPolicy(schema, policy);
  const lines = trimmed.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const first = lines[0] ?? '';
  const structuralOk = /^(graph|flowchart|sequenceDiagram|stateDiagram|classDiagram|erDiagram|journey|mindmap|timeline|gitGraph|gantt|pie|quadrantChart|requirementDiagram|C4Context|C4Container)/.test(first);
  return structuralOk
    ? buildResult({
        structuralOk: true,
        qualityTier,
        qualityVerdict: 'accepted',
        qualityScore: 92,
        qualityReasons: [],
        normalized: trimmed.endsWith('\n') ? trimmed : `${trimmed}\n`
      })
    : buildResult({
        structuralOk: false,
        qualityTier,
        qualityVerdict: 'blocked',
        qualityScore: 0,
        qualityReasons: ['missing valid mermaid diagram header'],
        message: 'Mermaid output is missing a valid diagram header.'
      });
}

function normalizeReviewIssues(raw: string): ReviewIssue[] {
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => /^[-*]\s+/.test(line))
    .map((line, index) => {
      const detail = line.replace(/^[-*]\s+/, '');
      return {
        id: `review-${index + 1}`,
        title: detail.slice(0, 32),
        detail,
        state: 'pending' as const
      };
    });
}

export function validateArtifact(raw: string, schema: ArtifactSchemaAsset, policy?: ArtifactValidationPolicy): ArtifactValidationResult {
  const { qualityTier } = resolveArtifactValidationPolicy(schema, policy);
  switch (schema.kind) {
    case 'markdown':
    case 'text':
      return validateMarkdown(raw, schema, policy);
    case 'mermaid':
      return validateMermaid(raw, schema, policy);
    case 'ui-preview':
      return parseUiPreviewSpec(raw)
        ? buildResult({
            structuralOk: true,
            qualityTier,
            qualityVerdict: 'accepted',
            qualityScore: 90,
            qualityReasons: [],
            normalized: raw
          })
        : buildResult({
            structuralOk: false,
            qualityTier,
            qualityVerdict: 'blocked',
            qualityScore: 0,
            qualityReasons: ['ui preview json cannot be parsed'],
            message: 'UI Preview JSON cannot be parsed.'
          });
    case 'review-issues': {
      const issues = normalizeReviewIssues(raw);
      return issues.length
        ? buildResult({
            structuralOk: true,
            qualityTier,
            qualityVerdict: issues.length >= 2 ? 'accepted' : 'degraded',
            qualityScore: issues.length >= 4 ? 92 : issues.length >= 2 ? 78 : 58,
            qualityReasons: issues.length >= 2 ? [] : ['review issue list is too short'],
            normalized: raw,
            issues,
            message: issues.length >= 2 ? undefined : 'Review issue list is too short.'
          })
        : buildResult({
            structuralOk: false,
            qualityTier,
            qualityVerdict: 'blocked',
            qualityScore: 0,
            qualityReasons: ['review issue list is empty or not a markdown list'],
            message: 'Review issue list is empty or not a Markdown list.'
          });
    }
    case 'openspec-handoff':
      return raw.trim()
        ? buildResult({
            structuralOk: true,
            qualityTier,
            qualityVerdict: 'accepted',
            qualityScore: 80,
            qualityReasons: [],
            normalized: raw
          })
        : buildResult({
            structuralOk: false,
            qualityTier,
            qualityVerdict: 'blocked',
            qualityScore: 0,
            qualityReasons: ['openspec handoff output is empty'],
            message: 'OpenSpec handoff output is empty.'
          });
    default:
      return buildResult({
        structuralOk: true,
        qualityTier,
        qualityVerdict: 'accepted',
        qualityScore: 75,
        qualityReasons: [],
        normalized: raw
      });
  }
}
