import { describe, expect, it } from 'vitest';
import { validateArtifact } from '../../src/shared/artifact-validators.js';

describe('validateArtifact', () => {
  it('accepts markdown with required headings and returns a quality score', () => {
    const result = validateArtifact([
      '# 标题',
      '',
      '## 当前目标',
      '- 当前输入来自 `input/notes/` 与 `01-requirements/`，需要整理成可继续推进的阶段文档。',
      '- 输出写入 `02-solution/summary.md`，并保留 review owner、evidence path 与 output contract。',
      '',
      '## 执行动作',
      '- 1. verify 当前范围和验收口径；2. recover 或 merge 冲突后再写回；3. export 当前结果并记录日志。',
      '- 文档必须写清输入、输出、约束、风险、恢复路径和下一步动作，避免只保留摘要。'
    ].join('\n'), {
      id: 'md',
      title: 'Markdown',
      kind: 'markdown',
      requiredHeadings: ['#', '##']
    });

    expect(result.ok).toBe(true);
    expect(result.qualityVerdict).toBe('accepted');
    expect(result.qualityScore).toBeGreaterThan(0);
  });

  it('rejects invalid mermaid text', () => {
    const result = validateArtifact('not-a-diagram', {
      id: 'mm',
      title: 'Mermaid',
      kind: 'mermaid'
    });

    expect(result.ok).toBe(false);
    expect(result.qualityVerdict).toBe('blocked');
  });

  it('extracts review issues from markdown list', () => {
    const result = validateArtifact('- 第一项问题\n- 第二项问题\n', {
      id: 'issues',
      title: 'Issues',
      kind: 'review-issues'
    });

    expect(result.ok).toBe(true);
    expect(result.issues).toHaveLength(2);
  });

  it('rejects markdown below the minimum length', () => {
    const result = validateArtifact('# Title\n\n## Context\n\n- Short\n', {
      id: 'short-md',
      title: 'Short Markdown',
      kind: 'markdown',
      requiredHeadings: ['# Title', '## Context'],
      minimumLength: 80
    });

    expect(result.ok).toBe(false);
    expect(result.message).toMatch(/minimum length/i);
    expect(result.qualityVerdict).toBe('blocked');
  });

  it('blocks deterministic fallback markers for strict core artifacts', () => {
    const result = validateArtifact(
      [
        '# 原始需求',
        '',
        '## 目标用户',
        '- This section was generated by the deterministic fallback template.',
        '- Fill in concrete users, constraints, evidence, and execution details before delivery.',
        '',
        '## 核心问题',
        '- This section was generated by the deterministic fallback template.'
      ].join('\n'),
      {
        id: 'requirements-discovery',
        title: '原始需求',
        kind: 'markdown',
        requiredHeadings: ['# 原始需求', '## 目标用户', '## 核心问题'],
        minimumLength: 80
      }
    );

    expect(result.ok).toBe(false);
    expect(result.structuralOk).toBe(true);
    expect(result.qualityVerdict).toBe('blocked');
    expect(result.qualityScore).toBeLessThan(30);
    expect(result.qualityReasons.join(' ')).toMatch(/deterministic fallback/i);
  });

  it('degrades discovery artifacts that miss success criteria and next actions', () => {
    const result = validateArtifact(
      [
        '# 原始需求',
        '',
        '## 目标用户',
        '- 内容团队成员需要一个文档工作台。',
        '- 负责人希望快速整理想法。',
        '',
        '## 核心问题',
        '- 目前需求输入分散，容易遗漏。',
        '- 文档难以进入后续阶段。',
        '',
        '## 核心价值',
        '- 系统会生成结构化文档。',
        '- 系统会帮助沉淀内容。',
        '',
        '## 显性限制',
        '- 当前聚焦桌面端。',
        '- 输出以 Markdown 为主。',
        '',
        '## 待确认问题',
        '- 是否支持多人协作？',
        '- 是否支持更多导出格式？'
      ].join('\n'),
      {
        id: 'requirements-discovery',
        title: '原始需求',
        kind: 'markdown',
        requiredHeadings: ['# 原始需求', '## 目标用户', '## 核心问题', '## 核心价值', '## 显性限制', '## 待确认问题'],
        minimumLength: 200
      }
    );

    expect(result.ok).toBe(false);
    expect(result.structuralOk).toBe(true);
    expect(result.qualityVerdict).toBe('degraded');
    expect(result.qualityReasons.join(' ')).toMatch(/success criteria|next clarification actions/i);
    expect(result.repairHints?.join(' ')).toMatch(/成功标准|下一步/);
  });

  it('accepts clarify artifacts with concrete operations, contracts, and next-stage inputs', () => {
    const result = validateArtifact(
      [
        '# 需求澄清',
        '',
        '## 使用方式',
        '- 项目负责人先在欢迎页创建工程，再进入主工作台补齐 `01-requirements/01-原始需求.md`，确认范围、交付对象、验收口径和风险边界已经完整落盘。',
        '- 审查负责人在主工作台查看阶段、未保存数量、任务抽屉和 AI 会话建议，确认没有阻断项后再进入思路地图梳理关键决策与证据。',
        '- 交付负责人进入流编排页调整节点顺序、子流程和导出映射，再返回主工作台继续生成文档、导出交付包并完成最终检查。',
        '',
        '## 输入与输出',
        '- 输入包括一句话目标、`input/notes/*.md`、`flows/main.flow.json`、资源中心模板、规则中心条目以及本地审查记录。',
        '- 输出工件包括 `01-requirements/*.md`、`02-solution/*.md`、`03-stage-plans/*.md`、`03-openspec/specs/*` 和导出清单 `exports/manifest.json`。',
        '- 输出格式必须覆盖 `md`、`txt`、`pdf` 与 `openspec`；输出目录结构固定为 `01-requirements/`、`02-solution/`、`03-stage-plans/`、`03-openspec/exports/` 四层。',
        '- 文档结构必须写清输入源、处理动作、失败恢复、验收方式和责任人，避免只留下笼统摘要。',
        '',
        '## 关键约束',
        '- 当前必须支持桌面端本地运行、本地模型与远程模型切换、明确的权限边界以及无头浏览器访问限制。',
        '- 任何 AI 写回都不能静默覆盖人工修改；若检测到外部变更、冲突或低于 90 分的输出质量，系统必须阻断确认并要求修复。',
        '- 导出前必须通过 lint、unit、build、post-change-extreme validation 与输出质量门禁，且每一步都要保留运行证据。',
        '',
        '## 风险与边界',
        '- 当输入文档被外部修改、删除或锁定时，系统需要提示冲突并提供恢复、合并、重跑或回退路径。',
        '- 当连接器鉴权失败、模型超时、无头浏览器返回空内容或导出目录校验失败时，界面必须显示具体原因，不能退化成模糊的“未知错误”。',
        '- 第一阶段不做联网模板市场和多人实时协作；超出本地导入、公开互联网抓取和本地交付的能力都要显式降级。',
        '',
        '## 待确认问题',
        '- 下一阶段的方案文档是否必须同步写回编排节点说明、阶段芯片和导出映射，保证 UI 与运行语义完全一致？',
        '- 表格工件、审批记录和运行证据是否都需要在下一阶段作为交付输入基线继续流转，并进入最终 manifest？',
        '- 是否需要把关键失败恢复脚本也放入交付包，供另一个 AI 在无背景说明下直接复现整个流程？',
        '',
        '## 下一阶段输入',
        '- 这些澄清结果会作为下一阶段输入和交付基线，直接喂给方案文档、测试计划、编排节点配置和最终交付说明。',
        '- 下一阶段必须复用本文件中的输出目录结构、输出格式、失败恢复规则、质量门槛和证据路径，禁止重新定义一套不兼容合同。',
        '- 进入方案阶段前先验证 `npm run test:post-change-extreme`、`npm run review:output-quality -- <file>` 与导出清单检查都已通过。'
      ].join('\n'),
      {
        id: 'requirements-clarify',
        title: '需求澄清',
        kind: 'markdown',
        requiredHeadings: ['# 需求澄清', '## 使用方式', '## 输入与输出', '## 关键约束', '## 风险与边界', '## 待确认问题'],
        minimumLength: 240
      }
    );

    expect(result.ok).toBe(true);
    expect(result.qualityVerdict).toBe('accepted');
    expect(result.qualityScore).toBeGreaterThanOrEqual(84);
  });

  it('degrades strict clarify artifacts that omit explicit next-stage inputs', () => {
    const result = validateArtifact(
      [
        '# 需求澄清',
        '',
        '## 使用方式',
        '- 运营负责人在欢迎页创建工程后进入 `01-requirements/01-原始需求.md`，补齐范围、交付对象和验收方式。',
        '- 审查负责人在主工作台检查 `阶段`、未保存状态与 AI 侧栏提示，再决定是否继续细化当前范围并准备导出。',
        '- 编排负责人在流编排页调整节点、子流程和导出映射，再回到主工作台继续生成与审查文档。',
        '',
        '## 输入与输出',
        '- 输入包括 `input/notes/*.md`、`flows/main.flow.json`、`rules/project/*.md` 与本地审查记录。',
        '- 输出工件包括 `01-requirements/*.md`、`02-solution/*.md`、`03-stage-plans/*.md`、`03-openspec/specs/*` 与 `03-openspec/exports/` 下的交付包。',
        '- 输出格式必须覆盖 `md`、`txt`、`pdf` 与 `openspec`；输出目录结构固定为 `01-requirements/`、`02-solution/`、`03-stage-plans/`、`03-openspec/exports/` 四层。',
        '- 文档结构需要包含输入来源、处理动作、失败恢复、责任人和验收状态，避免交付阶段再次补写。',
        '',
        '## 关键约束',
        '- 当前只支持桌面端本地运行，联网市场先不启用，但 `browse_web` 无头浏览器必须只访问公开互联网地址。',
        '- 任意 AI 生成内容在覆盖人工修改前都必须进入合并保护；交付评分低于 90 时禁止阶段确认。',
        '- 导出前必须通过 lint、unit、build、post-change-extreme validation 与输出质量门禁，并保存证据。',
        '',
        '## 风险与边界',
        '- 如果输入目录缺失或文件被外部改写，系统必须提示冲突并要求恢复、合并或重跑。',
        '- 如果连接器鉴权失败或返回 401/403，资源中心必须明确显示认证缺失，而不是笼统提示未知失败。',
        '- 如果导出目录结构被改写、manifest 缺字段或证据包不完整，系统必须阻断交付并提示修复路径。',
        '',
        '## 待确认问题',
        '- 是否需要把审批记录同步写入 `artifacts/post-change-extreme-validation/` 作为长期证据？',
        '- 是否要为导出目录增加固定 manifest 模板，避免不同项目各自扩展？',
        '- 是否需要把失败恢复脚本也放进交付包，让另一个 AI 无需额外背景即可接手？'
      ].join('\n'),
      {
        id: 'requirements-clarify',
        title: '需求澄清',
        kind: 'markdown',
        requiredHeadings: ['# 需求澄清', '## 使用方式', '## 输入与输出', '## 关键约束', '## 风险与边界', '## 待确认问题'],
        minimumLength: 240
      }
    );

    expect(result.ok).toBe(false);
    expect(result.structuralOk).toBe(true);
    expect(result.qualityVerdict).toBe('degraded');
    expect(result.qualityReasons.join(' ')).toMatch(/next-stage inputs/i);
    expect(result.qualityScore).toBeLessThan(100);
  });

  it('accepts feature-list artifacts that use markdown tables instead of bullets', () => {
    const result = validateArtifact(
      [
        '# 功能清单',
        '',
        '## 工程初始化',
        '系统需要把欢迎页新建工程动作拆成可执行的原子功能，并且每一项都要落到明确目录、失败恢复和验收口径，而不是只写抽象名词。',
        '',
        '| 原子功能 | 触发 | 输入 | 输出 | 依赖 | 完成标准 | 失败恢复 | 验收口径 | 下一步动作 |',
        '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
        '| 创建工程目录结构 | 用户点击欢迎页“新建工程” | 一句话创意 | `input/`、`01-requirements/`、`02-solution/`、`03-openspec/exports/` | 本地文件权限 | 10 秒内创建目录并写入 manifest | 创建失败时提示重试并保留日志 | 四个目录和 manifest 都存在 | 进入原始需求编写 |',
        '| 初始化阶段基线 | 创建工程完成后自动执行 | `01-requirements/01-原始需求.md` 草稿 | 阶段、任务抽屉、未保存计数初始状态 | 工程初始化完成 | 初始状态与欢迎页入口一致 | 初始化失败时恢复空白工程并提示用户 | 阶段为 discover，未保存数为 0 | 允许继续生成需求澄清 |',
        '',
        '## 文档生成与质量门',
        '每个原子功能都必须把输入合同、输出合同、角色、约束、异常恢复、证据路径和下一步动作写进表格，确保另一个 AI 只看本文件就能继续执行。',
        '',
        '| 原子功能 | 触发 | 输入 | 输出 | 依赖 | 完成标准 | 失败恢复 | 验收口径 | 下一步动作 |',
        '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
        '| 生成功能树 | 用户点击“生成阶段草稿” | `01-requirements/01-原始需求.md`、`01-requirements/02-需求澄清.md` | `01-requirements/03-功能树.md` | discover 与 clarify 阶段均已通过质量门 | 文档覆盖用户视角、开发视角、异常路径和导出链路 | 输出低于 90 分时阻断并要求 repair | 标题、长度、路径、验收条件齐全 | 进入功能清单拆解 |',
        '| 生成功能清单 | 功能树已生成并通过校验 | `01-requirements/03-功能树.md` | `01-requirements/04-功能清单.md` | 功能树、规则中心条目、当前会话摘要 | 至少列出 8 个原子功能并覆盖编排层、AI harness、工件契约与错误恢复 | 修复失败时记录到 `artifacts/post-change-extreme-validation/` 并阻断阶段 | 表格字段完整，能直接转成实现任务 | 进入技术方案撰写 |',
        '| 生成技术方案 | 功能清单通过质量门后执行 | `01-requirements/04-功能清单.md`、`rules/project/` | `02-solution/01-技术方案.md` | 功能清单、约束和导出合同有效 | 模块边界、输入输出、权限、恢复与导出映射完整 | 冲突时进入 merge 或 rerun | 人工复核分不低于 90 分 | 准备进入 draft 阶段 |',
        '',
        '## 导出与恢复',
        '交付负责人需要依据本清单核对 `03-openspec/exports/`、运行证据和失败恢复策略，确保导出包、证据包、人工确认记录与阶段合同一致。',
        '',
        '| 原子功能 | 触发 | 输入 | 输出 | 依赖 | 完成标准 | 失败恢复 | 验收口径 | 下一步动作 |',
        '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
        '| 导出交付包 | draft、review、finalize 阶段结束后执行 | `02-solution/*.md`、`03-openspec/specs/*`、运行证据 | `md + txt + pdf + openspec` 交付包 | 导出映射、权限边界、人工确认记录 | 四类导出物与 manifest 对齐 | 导出失败时支持 retry、recover、rollback | manifest、文件数量和证据路径全部正确 | 进入人工复核与签收 |',
        '| 恢复失败运行 | 模型超时、浏览器失败或外部改写触发 | 最近 checkpoint、snapshot、artifact revision | 恢复后的阶段文档与事件日志 | checkpoint、merge proposal、runtime evidence | 5 分钟内恢复到可继续执行状态 | 若恢复失败则阻断并给出人工处理步骤 | 日志、证据和恢复文档都可追溯 | 重新触发当前阶段生成 |'
      ].join('\n'),
      {
        id: 'feature-list',
        title: '功能清单',
        kind: 'markdown',
        requiredHeadings: ['# 功能清单', '## 工程初始化', '## 文档生成与质量门', '## 导出与恢复'],
        minimumLength: 400
      }
    );

    expect(result.ok).toBe(true);
    expect(result.qualityVerdict).toBe('accepted');
    expect(result.qualityReasons).toEqual([]);
  });

  it('does not flag quoted TBD and TODO examples as placeholder leakage', () => {
    const result = validateArtifact(
      [
        '# 执行 SOP 与治理清单',
        '',
        '## 目标与范围',
        '- 本文档定义 `02-solution/02-执行SOP与治理清单.md` 的执行规则、输入输出、失败恢复和验收口径。',
        '- 所有步骤都必须保留证据、明确质量门，并为后续 `03-stage-plans/` 产物提供结构化基线。',
        '',
        '## 质量门',
        '- 文档完整性要求：通过 `markdownlint` 检查，且无 `TBD`、`TODO` 等占位符残留。',
        '- Acceptance requires no deterministic fallback marker, placeholder wording, empty section, or generic demo content.',
        '- 所有关键步骤都要写明输入、输出、验证方式、回滚条件和责任角色。',
        '',
        '## 运行证据',
        '- 执行后保留 `05-runbooks-and-evidence/` 中的日志、截图与检查结果。',
        '- 若验证失败，必须记录失败原因、重试次数和最终回滚动作。',
        '',
        '## 下一步',
        '- 继续补齐 `04-artifact-templates/`、`05-runbooks-and-evidence/` 与最终交付说明，确保另一个 AI 可直接复现。'
      ].join('\n'),
      {
        id: 'markdown-basic',
        title: 'Markdown 基础文档',
        kind: 'markdown',
        requiredHeadings: ['#']
      },
      {
        qualityTier: 'strict',
        minimumQualityScore: 72
      }
    );

    expect(result.qualityReasons.join(' ')).not.toMatch(/placeholder patterns detected/i);
  });
});
